[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Hotaran", email = "hotaran.d98@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "confluent-kafka>=2.15.0",
    "fastapi>=0.141.1",
    "uvicorn>=0.52.0",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "black>=26.5.1",
    "flake8>=7.3.0",
    "pytest>=9.1.1",
]